service: externals-layer
frameworkVersion: '2.64'
useDotenv: true
variablesResolutionMode: 20210326
configValidationMode: error

custom:
    stage: ${opt:stage, self:provider.stage}

provider:
    name: aws
    region: us-east-1
    stage: dev
    runtime: nodejs14.x
    lambdaHashingVersion: 20201221
    environment:

layers:
    External:
        path: ./lambda-layers-externals/
        name: external-${self:custom.stage}
        description: 'Common dependencies'
        compatibleRuntimes:
            - nodejs14.x
        retain: false

resources:
    Outputs:
        ExternalLayerExport:
            Value:
                Ref: ExternalLambdaLayer
            Export:
                Name: ExternalLambdaLayer-${self:provider.stage}
